import fs from 'node:fs';
import {pageSchema} from '../site/seo.mjs';
import {servicesFinal,pricingFinal,reviewsFinal,areasFinal,faqsFinal} from '../site/final-pages.mjs';
import {homepage,footerFinal,closingFinal} from '../site/final-home.mjs';
import {coverageMap} from '../site/map.mjs';
import {navigation,wordmark,simpleProcess,simpleCare} from '../site/components.mjs';
import {services,extras,cities,slug,homes,groups,money,address,faqs,source} from '../site/catalog.mjs';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const icon=(name='arrow')=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',spark:'<path d="m12 3 2.2 6.8L21 12l-6.8 2.2L12 21l-2.2-6.8L3 12l6.8-2.2Z"/>',check:'<path d="m5 12 4 4L19 6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',phone:'<path d="m5 3 4 5-2 3a16 16 0 0 0 6 6l3-2 5 4-2 3C9 21 3 15 2 5Z"/>',leaf:'<path d="M20 3c0 10-2 16-10 16a7 7 0 0 1-7-7C3 4 12 6 20 3Z"/><path d="M3 21 15 9"/>',home:'<path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8"/>',plus:'<path d="M12 5v14M5 12h14"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'})[name]||''}</svg>`;
const quote=(id='',label='Get a free quote',style='primary')=>`<a class="button ${style}" href="quote.html${id?'?service='+id:''}">${label}${icon()}</a>`;
const brand=wordmark;
const header=navigation;
const footer=footerFinal;
const cta=closingFinal;
const faqBlock=(items=faqs.slice(0,4))=>`<div class="faq-list">${items.map(([q,a])=>`<details><summary>${esc(q)}${icon('plus')}</summary><p>${esc(a)}</p></details>`).join('')}</div>`;
const sectionHead=(eyebrow,title,description='',link='')=>`<div class="section-heading"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>${link}</div>`;
const serviceCard=(s,i=0)=>`<article class="service-card" data-category="${s.category}" data-name="${esc(s.name.toLowerCase())}"><a class="service-image" href="${s.id}.html"><img src="${s.image}" alt="${esc(s.name)} service illustration" width="880" height="660" loading="lazy"><span class="image-action" aria-label="View ${esc(s.name)}">${icon()}</span>${i===0?'<span class="image-tag">THE WHOLE-HOME RESET</span>':''}</a><div class="service-title"><h3><a href="${s.id}.html">${s.name}</a></h3><a class="add-service" href="quote.html?service=${s.id}" aria-label="Get estimate for ${esc(s.name)}">${icon('plus')}</a></div><p>${s.tagline}</p><span class="service-price">${s.price}</span></article>`;
const serviceGrid=(list=services.slice(0,6))=>`<div class="service-grid">${list.map(serviceCard).join('')}</div>`;
const reviews=()=>`<section class="section container" id="reviews">${sectionHead('GOOD WORDS, FROM REAL HOMES','The kind of clean<br>people talk about.','','<a class="text-link" href="https://maps.app.goo.gl/ZdvdWPmDTeBtYeqAA" target="_blank" rel="noopener">Read our Google reviews '+icon()+'</a>')}<div class="review-grid">${[
 ['Jasleen Sagoo','Clean Nest Jalandhar offers excellent cleaning services! Their team is professional, thorough, and reliable, with great attention to detail.'],
 ['Shelly Bajwa','Everything was very carefully cleaned, put back and left the place feeling anew! Definitely recommend and will take up on their services again.'],
 ['gurjit bhangu','I booked for my house deep cleaning service while in New Zealand. I was worried about the service and kind of work but they did fantastic work.']
].map(([name,text])=>`<figure class="review"><span class="stars" role="img" aria-label="5 out of 5 stars">★★★★★</span><blockquote>“${esc(text)}”</blockquote><figcaption><span class="avatar">${name.split(' ').map(w=>w[0]).slice(0,2).join('').toUpperCase()}</span><span>${name}<small>Google review excerpt</small></span></figcaption></figure>`).join('')}</div></section>`;
const resultFiles=fs.readdirSync('assets/img/results').filter(f=>f.startsWith('before-after-')).sort();
const cropBox=f=>/before-after-0[24]-/.test(f)?'0 267 1000 585':f.includes('single')?'0 140 1000 615':'0 0 1000 780';
const resultCard=(f,i)=>`<button class="result-card" data-lightbox="assets/img/results/${f}" data-crop="${cropBox(f)}" aria-label="Open cleaning result ${i+1}"><span class="result-crop"><svg viewBox="${cropBox(f)}" role="img" aria-label="CleanNest cleaning result ${i+1}"><image href="assets/img/results/previews/${f.replace('.png','.webp')}" width="1000" height="1000"/></svg></span><span>${f.includes('single')?'Cleaning result':'Before & after'} ${icon()}</span></button>`;
const lightbox=`<dialog id="lightbox" class="lightbox" aria-label="Cleaning result"><button class="dialog-close" aria-label="Close image">×</button><div class="lightbox-photo"><svg viewBox="0 0 1000 780" role="img" aria-label="Selected CleanNest cleaning result"><image width="1000" height="1000"/></svg></div></dialog>`;
function home(){return homepage({simpleProcess,simpleCare,faqBlock});}
const pageIntro=(tag,title,sub='')=>`<section class="page-intro container"><span class="eyebrow">${tag}</span><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</section>`;
function servicesPage(){return servicesFinal();}
function detail(s){return `<section class="service-hero container"><div><a class="breadcrumb" href="services.html">← All services</a><span class="eyebrow">${s.category.toUpperCase()} · JALANDHAR & NEARBY</span><h1>${s.name}<br><em>done thoughtfully.</em></h1><p>${s.tagline}</p><span class="detail-price">${s.price}</span>${quote(s.id,'Build my estimate')}<span class="muted">Final scope and price confirmed before booking.</span></div><img src="${s.image}" alt="${s.name} service illustration" width="880" height="660" fetchpriority="high"></section><section class="section container detail-layout"><div><span class="eyebrow">THE DETAILS MATTER</span><h2>What’s included</h2><ul class="inclusion-grid">${s.includes.map(t=>`<li>${icon('check')}<span>${esc(t)}</span></li>`).join('')}</ul><p class="muted">Tell us about delicate materials, existing damage or particular concerns before the visit. We’ll agree the scope and suitable treatment with you.</p></div><aside class="note-card"><span class="eyebrow">MADE FOR YOUR SPACE</span><h3>A clear plan.<br>Before we begin.</h3><p>Choose the size and options that fit your home. Add other services if needed, then review your estimate.</p>${quote(s.id,'Personalise my clean')}<p class="small">50% to confirm your booking. 50% after service.</p></aside></section><section class="section container faq-section"><div><span class="eyebrow">BEFORE WE VISIT</span><h2>A little more<br>peace of mind.</h2></div>${faqBlock(s.faqs.length?s.faqs:faqs.slice(0,4))}</section><section class="section container">${sectionHead('WHILE WE’RE HERE','A little extra care')}${serviceGrid(services.filter(v=>v.id!==s.id).slice(0,3))}</section>${cta()}`;}
function pricePage(){return pricingFinal();}
function areas(){return areasFinal();}
function city(c,confirmed=true){return pageIntro('LOCAL SERVICE · PERSONAL ATTENTION',`A cleaner space<br>in ${c}.`,confirmed?`Professional home and commercial cleaning in ${c}, delivered by our Jalandhar-based team.`:`Looking for cleaning in ${c}? Contact our Jalandhar team to check coverage for your exact location.`)+`<section class="container"><div class="price-callout"><div><h2>${confirmed?'Tell us about your space.':'Let’s check your location.'}</h2><p>Share your locality, home size and cleaning needs. We’ll confirm the scope, price and available date on WhatsApp.</p></div>${quote('','Get an estimate')}</div></section><section class="section container">${sectionHead('CLEANING, YOUR WAY',`Popular services in ${c}`)}${serviceGrid()}</section><section class="section container faq-section"><div><span class="eyebrow">PLAN YOUR VISIT</span><h2>Local care.<br>Clear expectations.</h2></div>${faqBlock([[`How do I arrange cleaning in ${c}?`,`Build an estimate and include ${c} and your locality in the request. Our team will confirm travel arrangements, exact scope and a suitable date before booking.`],faqs[4],faqs[5]])}</section>${cta()}`;}
function contact(){return pageIntro('WE’RE HERE TO HELP','Let’s talk<br>about your space.','A quick question or a whole-home reset. Our local team is ready to help.')+`<section class="container contact-grid"><div class="contact-panel"><span class="eyebrow">START A CONVERSATION</span><a href="tel:+917610000654">${icon('phone')}<span><small>Call or WhatsApp</small>+91 76100 00654</span>${icon()}</a><a href="mailto:cleannestclub@gmail.com">${icon('mail')}<span><small>Email us</small>cleannestclub@gmail.com</span>${icon()}</a><div class="contact-line">${icon('clock')}<span><small>Working hours</small>9 AM–8 PM, seven days a week</span></div><p class="small">Same-day appointments are subject to availability.</p>${quote('','Build a cleaning estimate')}</div><div class="office-panel"><span class="eyebrow">OUR JALANDHAR OFFICE</span><h2>A local team,<br>close to home.</h2><address>${address}</address><a class="text-link" href="https://maps.app.goo.gl/ZdvdWPmDTeBtYeqAA" target="_blank" rel="noopener">Get directions ${icon()}</a><hr><p>Serving ${cities.join(', ')}.</p><a class="text-link" href="areas-we-serve.html">See service areas ${icon()}</a></div></section>${cta()}`;}
function about(){return pageIntro('A LITTLE ABOUT CLEANNEST','Care you can see.<br>People you can trust.','Professional home and commercial cleaning, rooted in Jalandhar.')+`<section class="container care-section"><div class="care-image"><img src="assets/img/editorial/hero.webp" alt="A calm, clean living room — illustrative interior" width="1536" height="1024"></div><div class="care-copy"><span class="eyebrow">OUR APPROACH</span><h2>Your home deserves<br>thoughtful hands.</h2><p>A good clean is about the details: the edge of a tile, the fabric of a favourite sofa, the way everything is put back afterwards.</p><p>Our trained, background-checked team combines professional equipment with care for your home. We explain the scope and price before we begin, and keep you informed throughout.</p><a class="text-link" href="contact.html">Meet your local team ${icon()}</a></div></section><section class="section container"><div class="process-grid">${[['shield','People you can trust','Trained and background-checked professionals who treat your space with respect.'],['leaf','Care that fits your home','Suitable products and cleaning methods, with attention to children, pets and sensitive surfaces.'],['check','We stand by our work','If we miss an area in the agreed scope, tell us. We’ll arrange a free re-clean.']].map(([i,t,p])=>`<article>${icon(i)}<h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>${reviews()}${cta()}`;}
function quotePage(){return pageIntro('A FEW TAPS TO A FRESH START','Your home.<br>Your estimate.','Pick your services. We’ll take it from there.')+`<section class="container quote-layout" id="quote-builder"><div class="quote-main concentric"><ol class="quote-steps" aria-label="Quote progress"><li data-step-label="0">01 <span>Services</span></li><li data-step-label="1">02 <span>Details</span></li><li data-step-label="2">03 <span>About you</span></li><li data-step-label="3">04 <span>Estimate</span></li></ol><form id="quote-form"><div id="quote-stage"></div><div class="quote-navigation"><button class="button secondary" type="button" id="quote-back">← Back</button><button class="button primary" type="submit" id="quote-next">Next →</button></div></form><noscript><p>The quote builder needs JavaScript. <a href="https://wa.me/917610000654">Get a quote on WhatsApp</a> or call <a href="tel:+917610000654">+91 76100 00654</a>.</p></noscript></div></section>`;}
function tidyMain(html){return html.replace(/<script\b[\s\S]*?<\/script>/g,'').replace(/<style\b[\s\S]*?<\/style>/g,'').replace(/\s(?:class|style|id|data-[\w-]+)="[^"]*"/g,'').replace(/<svg\b[\s\S]*?<\/svg>/g,'').replace(/<h1\b[^>]*>[\s\S]*?<\/h1>/,'').replaceAll('href="../','href="').replaceAll('src="../','src="');}
function legacy(name,p){if(name.startsWith('blog/'))return pageIntro('THE CLEANING JOURNAL',esc(p.h1||p.title.split('|')[0]))+`<article class="container prose">${tidyMain(p.main)}</article>`;return pageIntro('CLEANNEST',esc(p.h1||p.title.split('|')[0]))+`<article class="container prose">${tidyMain(p.main)}</article>`;}
const pages=new Map();
for(const [file,p] of Object.entries(source.pages)) pages.set(file,{...p,body:legacy(file,p)});
const set=(file,title,body,description)=>pages.set(file,{...source.pages[file],title,body,description:description||source.pages[file]?.description||title});
set('index.html','Deep Cleaning Services in Jalandhar | CleanNest',home(),'Thoughtful home and commercial cleaning in Jalandhar and nearby cities. Explore services, real results and build a free WhatsApp cleaning estimate.');
set('services.html','Home & Commercial Cleaning Services | CleanNest',servicesPage());
for(const s of services)set(s.id+'.html',source.pages[s.id+'.html']?.title||s.name+' in Jalandhar | CleanNest',detail(s));
set('reviews.html','CleanNest Reviews | Google & Justdial Customer Feedback',reviewsFinal(),'Read CleanNest customer review excerpts and explore our Google and Justdial profiles. Professional cleaning in Jalandhar and nearby cities.');
set('pricing.html','Cleaning Prices & Free Estimates | CleanNest',pricePage());
set('areas-we-serve.html','Cleaning Service Areas in Punjab | CleanNest',areas());
for(const c of cities)set(slug(c)+'.html',`Professional Cleaning in ${c} | CleanNest`,city(c),`Home, kitchen, bathroom, sofa and commercial cleaning in ${c}. Get a tailored estimate from CleanNest’s Jalandhar-based team.`);
for(const c of ['Dasuya','Hariana'])set(slug(c)+'.html',`Cleaning Enquiries in ${c} | CleanNest`,city(c,false),`Contact CleanNest to check cleaning availability for your location in ${c}. Scope, travel and booking dates confirmed on WhatsApp.`);
set('results.html','Real Before & After Cleaning Results | CleanNest',pageIntro('OUR WORK, UP CLOSE','The difference<br>you can see.','Authentic before-and-after photographs from CleanNest’s existing project gallery.')+`<section class="container results-grid gallery-all">${resultFiles.map(resultCard).join('')}</section>${cta()}`);
set('contact.html','Contact CleanNest | Cleaning Services in Jalandhar',contact());
set('about.html','About CleanNest | Your Local Cleaning Team',about());
set('faqs.html','Cleaning & Booking Questions | CleanNest',faqsFinal());
set('quote.html','Build Your Free Cleaning Estimate | CleanNest',quotePage(),'Personalise your cleaning with home size and optional extras. See an itemized estimate and send your request to CleanNest on WhatsApp.');
set('blog/index.html','Cleaning Journal & Home Care Guides | CleanNest',pageIntro('THE CLEANING JOURNAL','A little know-how.<br>A happier home.','Practical guides to caring for your space between professional cleans.')+`<section class="container journal-grid">${Object.entries(source.pages).filter(([f,p])=>f.startsWith('blog/')&&p.main).map(([f,p])=>`<article class="journal-card"><span class="eyebrow">HOME CARE GUIDE</span><h2><a href="${f}">${esc(p.h1||p.title.split('|')[0])}</a></h2><p>${esc(p.description)}</p><a class="text-link" href="${f}">Read the guide ${icon()}</a></article>`).join('')}</section>`);
const aliases=Object.entries(source.pages).filter(([f,p])=>f.startsWith('blog/')&&f!=='blog/index.html'&&!p.main).map(([f])=>f);
for(const f of aliases)set(f,'Cleaning Prices & Booking Information | CleanNest',pageIntro('CLEANNEST GUIDES','Find your cleaning<br>and pricing information.','Our current prices and booking details are on the pricing page.')+`<div class="container error-actions"><a class="button primary" href="pricing.html">See the current rate card ${icon()}</a></div>`);
set('404.html','Page Not Found | CleanNest',pageIntro('A LITTLE OUT OF PLACE','Let’s get you<br>back home.','This page may have moved. Your fresh start is still here.')+`<div class="container error-actions"><a class="button primary" href="/">Back to home ${icon()}</a><a class="button secondary" href="services.html">Explore services</a></div>`);
for(const [file,p] of pages){
 const root=file.startsWith('blog/')?'../':'';
 const canonical='https://cleannest.in/'+(aliases.includes(file)?'pricing.html':file==='index.html'?'':file);
 const s=services.find(s=>file===s.id+'.html');
 const schema=pageSchema({file,page:p,canonical,service:s,isArticle:file.startsWith('blog/')&&file!=='blog/index.html'&&!aliases.includes(file)});
 let html=`<!doctype html><html lang="en-IN" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(p.title)}</title><meta name="description" content="${esc(p.description)}"><link rel="canonical" href="${canonical}"><meta name="theme-color" content="#F8F7F4"><meta property="og:type" content="website"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://cleannest.in/assets/img/editorial/hero.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/img/wordmark.svg"><link rel="preload" href="assets/fonts/Ultima.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="assets/site.css"><link rel="stylesheet" href="assets/refinements.css"><link rel="stylesheet" href="assets/final.css?v=faqs1"><link rel="stylesheet" href="assets/pages.css?v=faqs1"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script><script src="assets/site.js" defer></script><script src="assets/final.js?v=faqs1" defer></script>${file==='quote.html'?'<script type="module" src="assets/quote-flow.js"></script>':''}${file==='404.html'?'<meta name="robots" content="noindex">':''}</head><body class="${file==='index.html'?'home-final':''}">${header(file)}<main id="main">${p.body}</main>${footer()}${lightbox}</body></html>`;
 if(root) html=html.replace(/(href|src)="(?!https?:|mailto:|tel:|#|\/)([^"]+)"/g,(_,attr,value)=>`${attr}="${root}${value}"`);
 fs.writeFileSync(file,html.replace(/[\t ]+$/gm,'')+'\n');
}
fs.writeFileSync('assets/catalog.json',JSON.stringify({services,extras,groups,homes,cities,kitchenIncludesChimney:false}));
fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...pages.keys()].filter(f=>!['404.html','quote.html',...aliases].includes(f)).map(f=>`<url><loc>https://cleannest.in/${f==='index.html'?'':f}</loc></url>`).join('')+'</urlset>\n');
console.log(`Built ${pages.size} static pages and shared pricing data.`);
