import fs from 'node:fs';
import {resultContext} from '../site/results.mjs';
import {buildStyles,buildScripts,buildQuoteClient} from './styles.mjs';
const stylesheets=await buildStyles();
const scripts=buildScripts();
import {blogArticles,renderArticle} from '../site/blog.mjs';
import {redirects} from '../site/redirects.mjs';
import {cityPage} from '../site/city-content.mjs';
import {serviceContent,safeInclusions} from '../site/service-content.mjs';
import {businessInfo} from '../site/business.mjs';
import {pageSchema} from '../site/seo.mjs';
import {servicesFinal,pricingFinal,reviewsFinal,areasFinal,faqsFinal} from '../site/final-pages.mjs';
import {homepage,footerFinal,closingFinal,fromPrice} from '../site/final-home.mjs';
import {coverageMap} from '../site/map.mjs';
import {glyph,navigation,wordmark,simpleProcess,simpleCare} from '../site/components.mjs';
import {services,extras,cities,slug,homes,groups,money,supplements,address,faqs,faqSections,source} from '../site/catalog.mjs';
const clientCatalog={services:services.map(({includes,faqs,...service})=>service),extras,groups,homes,cities,supplements,kitchenIncludesChimney:false};
const clientScript=buildQuoteClient(clientCatalog);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const icon=(name='arrow')=>['mail','help','whatsapp','instagram','chevron'].includes(name)?glyph(name):`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',spark:'<path d="m12 3 2.2 6.8L21 12l-6.8 2.2L12 21l-2.2-6.8L3 12l6.8-2.2Z"/>',check:'<path d="m5 12 4 4L19 6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',phone:'<path d="m5 3 4 5-2 3a16 16 0 0 0 6 6l3-2 5 4-2 3C9 21 3 15 2 5Z"/>',leaf:'<path d="M20 3c0 10-2 16-10 16a7 7 0 0 1-7-7C3 4 12 6 20 3Z"/><path d="M3 21 15 9"/>',home:'<path d="m3 10 9-7 9 7M5 9v12h14V9M9 21v-8h6v8"/>',plus:'<path d="M12 5v14M5 12h14"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'})[name]||''}</svg>`;
const quote=(id='',label='Get a free quote',style='primary')=>`<a class="button ${style}" href="quote.html${id?'?service='+id:''}">${label}${icon()}</a>`;
const brand=wordmark;
const header=navigation;
const footer=footerFinal;
const cta=closingFinal;
const faqBlock=(items=faqs.slice(0,4))=>`<div class="faq-list">${items.map(([q,a])=>`<details><summary>${esc(q)}${glyph('chevron')}</summary><p>${esc(a)}</p></details>`).join('')}</div>`;
const sectionHead=(eyebrow,title,description='',link='')=>`<div class="section-heading"><div><span class="eyebrow">${eyebrow}</span><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>${link}</div>`;
const serviceCard=s=>`<article class="service-card" data-category="${s.category}" data-name="${esc(s.name.toLowerCase())}"><a class="service-image" href="${s.id}.html"><img src="${s.image}" alt="${esc(s.name)} service illustration" width="880" height="660" loading="lazy"><span class="image-action" aria-label="View ${esc(s.name)}">${icon()}</span>${s.id==='full-house-cleaning'?'<span class="image-tag">THE WHOLE-HOME RESET</span>':''}</a><div class="service-title"><h3><a href="${s.id}.html">${s.name}</a></h3><a class="add-service" href="quote.html?service=${s.id}" aria-label="Get estimate for ${esc(s.name)}">${icon('plus')}</a></div><p>${s.tagline}</p><span class="service-price">${fromPrice(s)}</span></article>`;
const serviceGrid=(list=services.slice(0,6))=>`<div class="service-grid">${list.map(serviceCard).join('')}</div>`;
const reviews=()=>`<section class="section container" id="reviews">${sectionHead('GOOD WORDS, FROM REAL HOMES','The kind of clean<br>people talk about.','','<a class="text-link" href="'+businessInfo.map+'" target="_blank" rel="noopener">Read our Google reviews '+icon()+'</a>')}<div class="review-grid">${[
 ['Jasleen Sagoo','Clean Nest Jalandhar offers excellent cleaning services! Their team is professional, thorough, and reliable, with great attention to detail.'],
 ['Shelly Bajwa','Everything was very carefully cleaned, put back and left the place feeling anew! Definitely recommend and will take up on their services again.'],
 ['gurjit bhangu','I booked for my house deep cleaning service while in New Zealand. I was worried about the service and kind of work but they did fantastic work.']
].map(([name,text])=>`<figure class="review"><span class="stars" role="img" aria-label="5 out of 5 stars">★★★★★</span><blockquote>“${esc(text)}”</blockquote><figcaption><span class="avatar">${name.split(' ').map(w=>w[0]).slice(0,2).join('').toUpperCase()}</span><span>${name}<small>Google review excerpt</small></span></figcaption></figure>`).join('')}</div></section>`;
const resultFiles=fs.readdirSync('assets/img/results').filter(f=>f.startsWith('before-after-')).sort();
const cropBox=f=>/before-after-0[24]-/.test(f)?'0 267 1000 585':f.includes('single')?'0 140 1000 615':'0 0 1000 780';
const resultBase=f=>f.replace('.png','');
const cropStyle=f=>{const [,y,,h]=cropBox(f).split(' ').map(Number);return `--result-ratio:1000/${h};--result-position:center ${y===0?'top':y===267?'center':'44%'}`;};
const resultPicture=(f,i)=>{const b=resultBase(f),context=resultContext(f);return `<picture><source type="image/avif" srcset="assets/img/results/responsive/${b}-480.avif 480w, assets/img/results/responsive/${b}-720.avif 720w, assets/img/results/responsive/${b}-880.avif 880w"><img src="assets/img/results/previews/${b}.webp" srcset="assets/img/results/responsive/${b}-480.webp 480w, assets/img/results/responsive/${b}-720.webp 720w, assets/img/results/previews/${b}.webp 880w" sizes="(max-width: 700px) calc(100vw - 44px), (max-width: 1100px) calc(50vw - 40px), 360px" alt="${context.subject} result ${i+1}" width="1000" height="${cropBox(f).split(' ')[3]}" loading="${i===0?'eager':'lazy'}" decoding="async"${i===0?' fetchpriority="high"':''}></picture>`;};
const resultCard=(f,i)=>{const b=resultBase(f),context=resultContext(f);return `<article class="result-entry"><button class="result-card" data-lightbox="assets/img/results/previews/${b}.webp" data-lightbox-avif="assets/img/results/responsive/${b}-880.avif" data-result-style="${cropStyle(f)}" aria-label="Open ${context.subject.toLowerCase()} result ${i+1}"><span class="result-crop" style="${cropStyle(f)}">${resultPicture(f,i)}</span><span>${context.subject} · ${i+1} ${icon()}</span></button>${context.service?`<a class="text-link" href="${context.service}.html">View service scope ${icon()}</a>`:''}</article>`;};
const lightbox=`<dialog id="lightbox" class="lightbox" aria-label="Cleaning result"><button class="dialog-close" aria-label="Close image">×</button><div class="lightbox-photo"><picture><source type="image/avif"><img alt="Selected CleanNest cleaning result" width="1000" height="780"></picture></div></dialog>`;
function home(){return homepage({simpleProcess,simpleCare,faqBlock});}
const pageIntro=(tag,title,sub='')=>`<section class="page-intro container"><span class="eyebrow">${tag}</span><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</section>`;
function servicesPage(){return servicesFinal();}
function detail(s){
 const content=serviceContent[s.id];
 const title=content.title;
 const includes=safeInclusions[s.id]||s.includes;
 const questions=[
  [`What should I share when booking ${title.toLowerCase()}?`,content.sections[0][1]],
  [`How is the price for ${title.toLowerCase()} confirmed?`,`The published guide is ${s.price}. Share the size, condition and access details for your job. We confirm the scope, price and available date before booking.`],
 ];
 if(s.id==='kitchen-cleaning')questions.push(faqSections[0][1][2]);
 if(s.id==='bathroom-cleaning')questions.push(['Can every hard-water mark be removed?','Limescale deposits and permanent surface damage can look similar. Share photos of the affected tiles, glass or fittings so the team can assess treatment. Complete stain removal is not guaranteed.']);
 if(s.id==='sofa-cleaning')questions.push(['When can I use my sofa again?','Drying depends on the fabric, treatment, weather and ventilation. Confirm the likely drying time with the team and wait until the sofa is dry before use.']);
 if(s.id==='ac-services')questions.push(['Does AC cleaning include gas refilling?','No. Gas refilling and repairs are separate from the cleaning scope. Tell us about cooling faults when requesting a quote.']);
 return `<section class="service-hero container"><div><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="services.html">Services</a> / ${esc(title)}</nav><span class="eyebrow">${s.category.toUpperCase()} · JALANDHAR & NEARBY</span><h1>${esc(title)}<br><em>in Jalandhar</em></h1><p>${s.tagline}</p><span class="detail-price">${s.price}</span>${quote(s.id,'Build my estimate')}<span class="muted">Final scope and price confirmed before booking.</span></div><img src="${s.image}" alt="${esc(s.name)} service illustration" width="880" height="660" fetchpriority="high"></section>
 <section class="section container detail-layout"><div><h2>What’s included in ${esc(title.toLowerCase())}</h2><ul class="inclusion-grid">${includes.map(t=>`<li>${icon('check')}<span>${esc(t)}</span></li>`).join('')}</ul><p class="muted">Tell us about delicate materials, existing damage or particular concerns before the visit. We’ll agree the scope and suitable treatment with you.</p></div><aside class="note-card"><h2>${esc(title)} prices</h2><p>${s.price}</p><p>See the <a class="text-link" href="pricing.html">central rate card</a> for units, options and ranges.</p>${quote(s.id,'Personalise my clean')}<p class="small">50% to confirm your booking. 50% after service.</p></aside></section>
 <section class="container service-guidance">${content.sections.map(([heading,body])=>`<section><h2>${esc(heading)}</h2><p>${esc(body)}</p></section>`).join('')}${content.guide?`<p><a class="text-link" href="blog/${content.guide}.html">Read our ${esc(title.toLowerCase())} guide ${icon()}</a></p>`:''}</section>
 <section class="section container faq-section"><div><span class="eyebrow">BEFORE WE VISIT</span><h2>${esc(title)} FAQs</h2></div>${faqBlock(questions)}</section>
 <section class="section container">${sectionHead('RELATED SERVICES','Other cleaning you may need')}${serviceGrid(content.related.map(id=>services.find(v=>v.id===id)))}</section>${cta()}`;
}
function pricePage(){return pricingFinal();}
function areas(){return areasFinal();}
function city(c){return cityPage(c);}
function contact(){return pageIntro('WE’RE HERE TO HELP','Let’s talk<br>about your space.','A quick question or a whole-home reset. Our local team is ready to help.')+`<section class="container contact-grid"><div class="contact-panel"><span class="eyebrow">START A CONVERSATION</span><a href="tel:${businessInfo.telephone}">${icon('phone')}<span><small>Call or WhatsApp</small>${businessInfo.displayPhone}</span>${icon()}</a><a href="mailto:${businessInfo.email}">${icon('mail')}<span><small>Email us</small>${businessInfo.email}</span>${icon()}</a><div class="contact-line">${icon('clock')}<span><small>Working hours</small>${businessInfo.hours}</span></div><p class="small">Same-day appointments are subject to availability.</p>${quote('','Build a cleaning estimate')}</div><div class="office-panel"><span class="eyebrow">OUR JALANDHAR OFFICE</span><h2>A local team,<br>close to home.</h2><address>${address}</address><a class="text-link" href="${businessInfo.map}" target="_blank" rel="noopener">Get directions ${icon()}</a><hr><p>Serving ${cities.join(', ')}.</p><a class="text-link" href="areas-we-serve.html">See service areas ${icon()}</a></div></section>${cta()}`;}
function about(){return pageIntro('A LITTLE ABOUT CLEANNEST','Care you can see.<br>People you can trust.','Professional home and commercial cleaning, rooted in Jalandhar.')+`<section class="container care-section"><div class="care-image"><img src="assets/img/editorial/hero.webp" alt="A calm, clean living room — illustrative interior" width="1536" height="1024"></div><div class="care-copy"><span class="eyebrow">OUR APPROACH</span><h2>Your home deserves<br>thoughtful hands.</h2><p>A good clean is about the details: the edge of a tile, the fabric of a favourite sofa, the way everything is put back afterwards.</p><p>Our trained, background-checked team combines professional equipment with care for your home. We explain the scope and price before we begin, and keep you informed throughout.</p><a class="text-link" href="contact.html">Meet your local team ${icon()}</a></div></section><section class="section container"><div class="process-grid">${[['shield','People you can trust','Trained and background-checked professionals who treat your space with respect.'],['leaf','Care that fits your home','Suitable products and cleaning methods, with attention to children, pets and sensitive surfaces.'],['check','We stand by our work','If we miss an area in the agreed scope, tell us. We’ll arrange a free re-clean.']].map(([i,t,p])=>`<article>${icon(i)}<h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>${reviews()}${cta()}`;}
const initialQuoteChoice=s=>`<label class="tap-service">${s.image?`<img src="${s.image}" alt="" width="100" height="75" loading="lazy">`:''}<span><strong>${s.name}</strong><small>${fromPrice(s)}</small></span><input type="checkbox" data-service="${s.id}"><span class="tap-check" aria-hidden="true">✓</span></label>`;
const initialQuoteStep=()=>`<h2 tabindex="-1">What needs cleaning?</h2><p>Tap everything you need.</p><div class="tap-service-grid">${services.slice(0,6).map(initialQuoteChoice).join('')}</div><details class="more-services"><summary>More services</summary><div class="tap-service-grid">${[...services.slice(6),...extras].map(initialQuoteChoice).join('')}</div></details><p class="selection-count" id="selection-count" aria-live="polite">0 services selected</p>`;
function quotePage(){return pageIntro('A FEW TAPS TO A FRESH START','Your home.<br>Your estimate.','Pick your services. We’ll take it from there.')+`<section class="container quote-layout" id="quote-builder" data-step="0" data-whatsapp="${businessInfo.whatsapp}"><div class="quote-main concentric"><ol class="quote-steps" aria-label="Quote progress"><li class="active" data-step-label="0" aria-current="step">01 <span>Services</span></li><li data-step-label="1">02 <span>Details</span></li><li data-step-label="2">03 <span>Contact</span></li><li data-step-label="3">04 <span>Estimate</span></li></ol><form id="quote-form"><div id="quote-stage">${initialQuoteStep()}</div><div class="quote-navigation"><button class="button secondary" type="button" id="quote-back" hidden>← Back</button><button class="button primary" type="submit" id="quote-next">Next →</button></div></form><noscript><p>The quote builder needs JavaScript. <a href="${businessInfo.whatsapp}">Get a quote on WhatsApp</a> or call <a href="tel:${businessInfo.telephone}">${businessInfo.displayPhone}</a>.</p></noscript></div></section>`;}
function tidyMain(html){return html.replace(/<script\b[\s\S]*?<\/script>/g,'').replace(/<style\b[\s\S]*?<\/style>/g,'').replace(/\s(?:class|style|id|data-[\w-]+)="[^"]*"/g,'').replace(/<svg\b[\s\S]*?<\/svg>/g,'').replace(/<h1\b[^>]*>[\s\S]*?<\/h1>/,'').replaceAll('href="../','href="').replaceAll('src="../','src="');}
function legacy(name,p){if(name.startsWith('blog/'))return pageIntro('THE CLEANING JOURNAL',esc(p.h1||p.title.split('|')[0]))+`<article class="container prose">${tidyMain(p.main)}</article>`;return pageIntro('CLEANNEST',esc(p.h1||p.title.split('|')[0]))+`<article class="container prose">${tidyMain(p.main)}</article>`;}
const pages=new Map();
for(const [file,p] of Object.entries(source.pages)) pages.set(file,{...p,body:legacy(file,p)});
const set=(file,title,body,description,options={})=>pages.set(file,{...source.pages[file],title,body,description:description||source.pages[file]?.description||title,...options});
set('index.html','CleanNest | Professional Cleaning in Jalandhar',home(),'Meet CleanNest, a Jalandhar-based home and commercial cleaning company. Explore clear service scopes, published starting prices, real work and tailored estimates.');
set('services.html','Cleaning Services Directory | CleanNest Jalandhar',servicesPage(),'Explore CleanNest home, commercial, room, furnishing, appliance and floor-care services. Compare scopes and starting prices before building an estimate.');
const serviceMetaDescriptions={
 'full-house-cleaning':'Full-home deep cleaning in Jalandhar from ₹4,500. Kitchen, bathrooms, floors and interior surfaces in one agreed scope, with optional sofa, AC and chimney add-ons.',
 'kitchen-cleaning':'Kitchen deep cleaning in Jalandhar from ₹2,490. Degreasing, cabinets, hob, backsplash, sink and exhaust cleaning with a clear optional chimney add-on.',
 'bathroom-cleaning':'Bathroom deep cleaning in Jalandhar from ₹890. Tile and grout scrubbing, fittings, glass, accessible drains and careful hard-water deposit assessment.',
 'sofa-cleaning':'Sofa cleaning in Jalandhar from ₹199 per seat. Choose Standard, Premium or Premium + steam treatment after the fabric and condition are checked.',
 'ac-services':'AC cleaning in Jalandhar from ₹490 per unit. Choose Standard or Snow foam deep jet cleaning; repairs and gas refilling are outside the cleaning scope.',
 'chimney-cleaning':'Kitchen chimney cleaning in Jalandhar from ₹690. Filter, baffle, grease and outer-body cleaning, booked separately or alongside a kitchen clean.',
};
for(const s of services)set(s.id+'.html',serviceContent[s.id].title+' in Jalandhar | CleanNest',detail(s),serviceMetaDescriptions[s.id]||`${serviceContent[s.id].title} in Jalandhar. Review the service scope, preparation, material limits and published pricing before requesting a CleanNest estimate.`);
set('reviews.html','CleanNest Reviews | Google & Justdial Customer Feedback',reviewsFinal(),'Read CleanNest customer review excerpts and explore our Google and Justdial profiles. Professional cleaning in Jalandhar and nearby cities.');
set('pricing.html','Deep Cleaning Price List in Jalandhar | CleanNest',pricePage(),'Deep cleaning price list in Jalandhar: official CleanNest ranges for homes, kitchens, bathrooms, sofas, appliances, floors and commercial spaces.');
set('areas-we-serve.html','Cleaning Service Areas in Punjab | CleanNest',areas());
for(const c of cities)set(slug(c)+'.html',c==='Jalandhar'?'Cleaning Company in Jalandhar | CleanNest':`Professional Cleaning in ${c} | CleanNest`,city(c),c==='Jalandhar'?'Contact CleanNest’s listed Jalandhar office, explore local cleaning services and published prices, and request a tailored estimate.':`Home, kitchen, bathroom, sofa and commercial cleaning enquiries in ${c}, handled by CleanNest’s Jalandhar-based team.`,{noindex:c!=='Jalandhar',cityClassification:c==='Jalandhar'?'KEEP + IMPROVE':'NOINDEX'});
for(const c of ['Dasuya','Hariana'])set(slug(c)+'.html',`Cleaning Enquiries in ${c} | CleanNest`,city(c,false),`Contact CleanNest to check cleaning availability for your location in ${c}. Scope, travel and booking dates confirmed on WhatsApp.`,{noindex:true,cityClassification:'MERGE'});
set('results.html','Real Before & After Cleaning Results | CleanNest',pageIntro('OUR WORK, UP CLOSE','The difference<br>you can see.','Authentic before-and-after photographs from CleanNest’s existing project gallery.')+`<section class="container results-grid gallery-all">${resultFiles.map(resultCard).join('')}</section><noscript><section class="container prose"><h2>All result photographs</h2><ul>${resultFiles.map((f,i)=>`<li><a href="assets/img/results/previews/${f.replace('.png','.webp')}">View cleaning result ${i+1}</a></li>`).join('')}</ul></section></noscript>${cta()}`,'See real CleanNest before-and-after cleaning results from bathrooms, floors and post-construction work in Jalandhar.');
set('contact.html','Contact CleanNest | Cleaning Services in Jalandhar',contact());
set('about.html','About CleanNest | Your Local Cleaning Team',about());
set('faqs.html','Cleaning & Booking Questions | CleanNest',faqsFinal());
set('quote.html','Build Your Free Cleaning Estimate | CleanNest',quotePage(),'Personalise your cleaning with home size and optional extras. See an itemized estimate and send your request to CleanNest on WhatsApp.');
for(const [id,article] of Object.entries(blogArticles)) {
 set('blog/'+id+'.html',article.title+' | CleanNest Blog',renderArticle(article),article.description);
 pages.get('blog/'+id+'.html').h1=article.title;
}
set('blog/index.html','Cleaning Journal & Home Care Guides | CleanNest',pageIntro('THE CLEANING JOURNAL','A little know-how.<br>A happier home.','Practical guides to caring for your space between professional cleans.')+`<section class="container journal-grid">${[...pages.entries()].filter(([f])=>f.startsWith('blog/')&&f!=='blog/index.html'&&blogArticles[f.slice(5,-5)]).map(([f,p])=>`<article class="journal-card"><span class="eyebrow">HOME CARE GUIDE</span><h2><a href="${f}">${esc(p.h1||p.title.split('|')[0])}</a></h2><p>${esc(p.description)}</p><a class="text-link" href="${f}">Read the guide ${icon()}</a></article>`).join('')}</section>`);
const aliases=Object.entries(source.pages).filter(([f,p])=>f.startsWith('blog/')&&f!=='blog/index.html'&&!p.main).map(([f])=>f);
for(const f of aliases)set(f,'Current Cleaning Information | CleanNest',pageIntro('CLEANNEST GUIDES','Find current<br>cleaning information.','Explore the current scope, pricing or booking guidance for this topic.')+`<div class="container error-actions"><a class="button primary" href="${redirects['/'+f]}">View current information ${icon()}</a></div>`);
set('404.html','Page Not Found | CleanNest',pageIntro('A LITTLE OUT OF PLACE','Let’s get you<br>back home.','This page may have moved. Your fresh start is still here.')+`<div class="container error-actions"><a class="button primary" href="/">Back to home ${icon()}</a><a class="button secondary" href="services.html">Explore services</a></div>`);
for(const [file,p] of pages){
 const root=file.startsWith('blog/')?'../':'';
 const canonical=businessInfo.url+(aliases.includes(file)?redirects['/'+file].slice(1):file==='index.html'?'':file);
 const s=services.find(s=>file===s.id+'.html');
 const schema=pageSchema({file,page:p,canonical,service:s,isArticle:file.startsWith('blog/')&&file!=='blog/index.html'&&!aliases.includes(file),metadata:blogArticles[file.slice(5,-5)]});
 const articleMeta=blogArticles[file.slice(5,-5)];
 const socialImage=articleMeta?.image?new URL(articleMeta.image.url||articleMeta.image,businessInfo.url).href:businessInfo.url+'assets/img/editorial/hero-collage.webp';
 let html=`<!doctype html><html lang="en-IN" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(p.title)}</title><meta name="description" content="${esc(p.description)}"><link rel="canonical" href="${canonical}"><meta name="theme-color" content="#F8FAFC"><meta property="og:type" content="${articleMeta?'article':'website'}"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${socialImage}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/png" sizes="64x64" href="assets/favicon.png"><link rel="apple-touch-icon" href="assets/apple-touch-icon.png"><noscript><style>.comparison-card:nth-child(n+3),.gallery-all .result-entry:nth-child(n+4){display:none}</style></noscript><link rel="preload" href="assets/fonts/Ultima.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="assets/fonts/DMSerifDisplay.woff2" as="font" type="font/woff2" crossorigin>${file==='quote.html'?'<link rel="preload" href="assets/fonts/Manrope.woff2" as="font" type="font/woff2" crossorigin>':''}${stylesheets.filter((_,i)=>i!==1||['services.html','pricing.html','reviews.html','areas-we-serve.html','faqs.html'].includes(file)).map(href=>`<link rel="stylesheet" href="${href}">`).join('')}<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>${scripts.map(src=>`<script src="${src}" defer></script>`).join('')}${file==='quote.html'?`<script type="module" src="${clientScript}"></script>`:''}${file==='404.html'||aliases.includes(file)||p.noindex?'<meta name="robots" content="noindex,follow">':''}</head><body class="${file==='index.html'?'home-final':''}">${header(file)}<main id="main">${p.body}</main>${footer()}${lightbox}</body></html>`;
 for(const homeLink of ['index.html','../index.html','/index.html','https://cleannest.in/index.html'])html=html.replaceAll('href="'+homeLink+'"','href="/"');
 if(root) html=html.replace(/(href|src)="(?!https?:|mailto:|tel:|#|\/)([^"]+)"/g,(_,attr,value)=>`${attr}="${root}${value}"`);
 fs.writeFileSync(file,html.replace(/[\t ]+$/gm,'')+'\n');
}
fs.writeFileSync('assets/catalog.json',JSON.stringify(clientCatalog));
fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...pages.entries()].filter(([f,p])=>!['404.html','quote.html',...aliases].includes(f)&&!p.noindex).map(([f])=>`<url><loc>${businessInfo.url}${f==='index.html'?'':f}</loc></url>`).join('')+'</urlset>\n');
console.log(`Built ${pages.size} static pages and shared pricing data.`);
